In [1]:
import numpy as np

### data types & attributes

In [3]:
### Numpy arrays
a1 = np.array([1,2,3]) ##创建一个一维的numpy数组

In [3]:
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]) ##创建一个二维的numpy数组

In [6]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) ##创建一个三维的numpy数组
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
import pandas as pd

In [10]:
df  =pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,5.0,6.0


In [6]:
type(a1)

numpy.ndarray

### 创建数组

In [11]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [12]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
zeros= np.zeros((2,3,4)) ##创建一个2行3列4层的全零数组
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
rang_array = np.arange(0,10,2) ##创建一个从0到10，步长为2的数组
rang_array

array([0, 2, 4, 6, 8])

In [42]:
random_array = np.random.randint(2,10,size=(2,5)) ##创建一个2行5列的随机整数数组，整数范围在2到10之间
random_array

array([[9, 4, 3, 9, 5],
       [6, 4, 5, 8, 3]], dtype=int32)

In [43]:
random_array.size

10

In [44]:
random_array.shape

(2, 5)

In [49]:
np.random.seed(20)
random_array_1 = np.random.random((5,3))
random_array_1
##设置随机数种子为0

array([[0.5881308 , 0.89771373, 0.89153073],
       [0.81583748, 0.03588959, 0.69175758],
       [0.37868094, 0.51851095, 0.65795147],
       [0.19385022, 0.2723164 , 0.71860593],
       [0.78300361, 0.85032764, 0.77524489]])

In [55]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.7555236 , 0.83889446, 0.03553703],
       [0.12144377, 0.89100806, 0.51509223],
       [0.92441901, 0.58124263, 0.77325639],
       [0.42267689, 0.82546475, 0.38540456],
       [0.35434596, 0.42807852, 0.39506518]])