In [1]:
import numpy as np

### data types & attributes

In [2]:
### Numpy arrays
a1 = np.array([1,2,3]) ##创建一个一维的numpy数组

In [3]:
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]) ##创建一个二维的numpy数组

In [6]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) ##创建一个三维的numpy数组
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
import pandas as pd

In [17]:
df  =pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,5.0,6.0
